services:
  angular-app:
    build:
      context: ./
      dockerfile: dockerfile.prod
      args:
        NODE_ENV: production
    image: angular-app
    restart: always
    ports:
      - "4200:4200"   # Asegúrate de que el puerto 80 esté expuesto
    container_name: angular-app
    networks:
      - angular-net

networks:
  angular-net:
    driver: bridge
