apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ng-teslo-shop
  name: ng-teslo-shop-service
spec:
  ports:
  - name: "4200"
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: ng-teslo-shop
  type: NodePort
status:
  loadBalancer: {}
