services:
  angular-teslo-shop:
    image: nruz176/angular-teslo-shop
    restart: always
    ports:
      - "4200:80"   # Asegúrate de que el puerto 80 esté expuesto
    container_name: angular-teslo-shop
    networks:
      - angular-net

networks:
  angular-net:
    driver: bridge
